/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staffff;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ishara Fernando
 */
public class CanteenBookshopAndLibraryRecords extends javax.swing.JFrame {
    
    Connection con = null; 
    PreparedStatement ps = null;
    ResultSet rs = null;



    /**
     * Creates new form CanteenBookshopAndLibraryRecords
     */
    public CanteenBookshopAndLibraryRecords() {
        initComponents();
        con = Database.connect();
        table();
    }
    
    
    
    public void table()
    {
        try
        {
            String sql = "SELECT InvoiceID, Month,Type,Cost FROM canteenbookshopandlibrary ";
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            cblrtable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (Exception e) {}
           
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbalrtitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cblrinid = new javax.swing.JTextField();
        cblrtype = new javax.swing.JTextField();
        cblrmonth = new javax.swing.JTextField();
        cblrcost = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cblrsubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cblrtable = new javax.swing.JTable();
        cblrupdate = new javax.swing.JButton();
        cblrdelete = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        maintitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbalrtitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbalrtitle.setText("Canteen,Book shop & Library Records");
        getContentPane().add(cbalrtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 350, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Invoice ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Type :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Month :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cost :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));
        getContentPane().add(cblrinid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 180, 50));
        getContentPane().add(cblrtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 180, 50));
        getContentPane().add(cblrmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 180, 40));
        getContentPane().add(cblrcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 180, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, -1, -1));

        cblrsubmit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cblrsubmit.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\Upload.png")); // NOI18N
        cblrsubmit.setText("Sumbit");
        cblrsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblrsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(cblrsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, -1, -1));

        cblrtable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cblrtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice ID", "Month", "Cost", "Type"
            }
        ));
        cblrtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cblrtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cblrtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 1170, 420));

        cblrupdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cblrupdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\Save.png")); // NOI18N
        cblrupdate.setText("Update");
        cblrupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblrupdateActionPerformed(evt);
            }
        });
        getContentPane().add(cblrupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 650, -1, -1));

        cblrdelete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cblrdelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\cancel.png")); // NOI18N
        cblrdelete.setText("Delete");
        cblrdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblrdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(cblrdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 650, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\a4.png")); // NOI18N
        jButton2.setText("Generate Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 750, -1, -1));

        jPanel1.setBackground(new java.awt.Color(162, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 169, 20), 4));

        maintitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        maintitle.setForeground(new java.awt.Color(255, 255, 255));
        maintitle.setText("Finance Management");
        maintitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(maintitle);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1820, 80));

        jPanel2.setBackground(new java.awt.Color(214, 222, 222));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 169, 20), 4));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1820, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FinanceMain  fm6 = new FinanceMain();
        fm6.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cblrsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblrsubmitActionPerformed
        String Month = cblrmonth.getText();
        String Cost = cblrcost.getText();
        String Type = cblrtype.getText();
        
         if(Month.isEmpty() || Cost .isEmpty() || Type.isEmpty() ){
            JOptionPane.showConfirmDialog(null,"Error!!!");
        }
        else{
            
        int x=JOptionPane.showConfirmDialog(null,"Do you want to add this record");
        if (x==0){
         
         
        try 
        {
            String q = "INSERT INTO `canteenbookshopandlibrary`(`Month`, `Cost`, `Type`) VALUES ('"+Month+"','" +Cost+"','"+Type+"' )";
            ps=con.prepareStatement(q);
            ps.execute();
            table();
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
        }
        }
         }
    }//GEN-LAST:event_cblrsubmitActionPerformed

    private void cblrtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cblrtableMouseClicked
        // table mouse click
        int r = cblrtable.getSelectedRow();
        String inid = cblrtable.getValueAt(r, 0).toString();
        String month = cblrtable.getValueAt(r, 1).toString();
        String cost = cblrtable.getValueAt(r, 2).toString();
        String type = cblrtable.getValueAt(r, 3).toString();
        
        cblrinid.setText(inid);
        cblrmonth.setText(month);
        cblrcost.setText(cost);
        cblrtype.setText(type);
    }//GEN-LAST:event_cblrtableMouseClicked

    private void cblrupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblrupdateActionPerformed
         // update
        String inid = cblrinid.getText();
        String month = cblrmonth.getText();
        String cost = cblrcost.getText();
        String type = cblrtype.getText();
        
        String q = "UPDATE `canteenbookshopandlibrary` SET Month ='"+month+"', Cost = '"+cost+"', Type = '"+type+"' where InvoiceID = '"+inid+"'";
        try{
        ps = con.prepareStatement(q);
        ps.execute();
        table();
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_cblrupdateActionPerformed

    private void cblrdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblrdeleteActionPerformed

        // Delete
        String inid = cblrinid.getText();
        String q = "DELETE from canteenbookshopandlibrary where InvoiceID =' "+inid+"'";
        try{
            ps = con.prepareStatement(q);
            ps.execute();
            table();
        }
        catch(Exception e)
        {
            
        }
        
        
    }//GEN-LAST:event_cblrdeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            cblrtable.print();
        } catch (PrinterException ex) {
            Logger.getLogger(CanteenBookshopAndLibraryRecords.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CanteenBookshopAndLibraryRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CanteenBookshopAndLibraryRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CanteenBookshopAndLibraryRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CanteenBookshopAndLibraryRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CanteenBookshopAndLibraryRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cbalrtitle;
    private javax.swing.JTextField cblrcost;
    private javax.swing.JButton cblrdelete;
    private javax.swing.JTextField cblrinid;
    private javax.swing.JTextField cblrmonth;
    private javax.swing.JButton cblrsubmit;
    private javax.swing.JTable cblrtable;
    private javax.swing.JTextField cblrtype;
    private javax.swing.JButton cblrupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maintitle;
    // End of variables declaration//GEN-END:variables
}
