package staffff;




import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class exam extends javax.swing.JFrame {

    /**
     * Creates new form exam
     */
    public exam() {
        initComponents();
        Update_Table();
    }
    DB j = new DB();

    String day;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1Insert = new javax.swing.JButton();
        jButton2Update = new javax.swing.JButton();
        jButton3Delete = new javax.swing.JButton();
        jButton4Search = new javax.swing.JButton();
        jButton1clear = new javax.swing.JButton();
        jButton1back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1print = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(160, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 160, 20), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1Insert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1Insert.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\Save.png")); // NOI18N
        jButton1Insert.setText("Save");
        jButton1Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1InsertActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, 40));

        jButton2Update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2Update.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\Upload.png")); // NOI18N
        jButton2Update.setText("Update");
        jButton2Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, 40));

        jButton3Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3Delete.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\delete16.png")); // NOI18N
        jButton3Delete.setText("Delete");
        jButton3Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 160, 40));

        jButton4Search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4Search.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\itmsearch.png")); // NOI18N
        jButton4Search.setText("Search");
        jButton4Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4SearchActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 160, 40));

        jButton1clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1clear.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\Floopy.png")); // NOI18N
        jButton1clear.setText("Clear");
        jButton1clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1clearActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 160, 40));

        jButton1back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1back.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\arrow-circle-315.png")); // NOI18N
        jButton1back.setText("Back");
        jButton1back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1backActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 750, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 810));

        jPanel2.setBackground(new java.awt.Color(214, 222, 222));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 160, 20), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("SubjectId");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Day");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Start Time");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Venue");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 250, 30));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 270, 30));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SubjectID", "Class", "Day", "Start Time", "End Time", "Venue"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 69, 1110, 480));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 260, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Class");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 180, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("End time");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 270, 30));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 250, 30));

        jButton1print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1print.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\1471468405_invoice.png")); // NOI18N
        jButton1print.setText("Print");
        jButton1print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1printActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1print, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 620, 170, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 92, 1620, 720));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 52, 923, -1));

        jPanel3.setBackground(new java.awt.Color(160, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 160, 20), 4));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EXAM TIMETABLES");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1620, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1InsertActionPerformed
        // TODO add your handling code here:
        String subjectId = jTextField1.getText();
        String Class = jTextField4.getText();
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
       //date = jDateChooser1.getDate();
       // JOptionPane.showConfirmDialog(null,date);
        day = sdf.format(date);

        //Date date;
        //date = jDateChooser1.getDate();
        //String dayString = sdf.format(date);
        
        
        String Start_time = jTextField3.getText();
        String End_Time = jTextField5.getText();
        
         

        String venue = jTextField2.getText();
         
         
        
         
         if(subjectId.isEmpty() || Start_time.isEmpty() || End_Time.isEmpty() || day.isEmpty() || venue.isEmpty() || Class.isEmpty()){
             JOptionPane.showConfirmDialog(null,"No complete");
         }
         else{
              int  x =JOptionPane.showConfirmDialog(null,"Do you want to add this record");
           if(x==0){
         
         
         try{
             j.con();
            j.putdata("INSERT INTO `exam_timetable`(`ExamSubjectID`, `Grade`, `ExamDay`, `Start ExamTime`, `End Exam Time`, `Venue`)" + "VALUES ('" +subjectId+"','"+Class+"','"+day+"','"+Start_time+"','"+End_Time+"','"+venue+"')");
             JOptionPane.showMessageDialog(rootPane, "Successfully");
             Update_Table();
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
             e.printStackTrace();
             
         }
           }
         }
       
        
    }//GEN-LAST:event_jButton1InsertActionPerformed

    private void jButton2UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2UpdateActionPerformed
        // TODO add your handling code here:
        String subjectId = jTextField1.getText();
         String Start_time = jTextField3.getText();
         String End_Time = jTextField5.getText();
         //Date date = new Date();
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
       //date = jDateChooser1.getDate();
       // JOptionPane.showConfirmDialog(null,date);
        day = sdf.format(date);

        //Date date;
        //dateSimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
        ////Date date;
        //date = jDateChooser1.getDate();
       // String dayString = sdf.format(date);
        
        //date = jDateChooser1.getDate();
        // day = sdf.format(date);
         
        
         String venue = jTextField2.getText();
         String Class = jTextField4.getText();
         try{
         j.con();
      
         j.putdata("UPDATE `exam_timetable` SET `Grade`='"+Class+"',`ExamDay`='"+day+"',`Start ExamTime`='"+Start_time+"',`End Exam Time`='"+End_Time+"',`Venue`='"+venue+"'  WHERE `ExamSubjectID`='"+subjectId+"'");
         JOptionPane.showMessageDialog(rootPane, "UPDATE");
         Update_Table();
         clear();
         }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
             e.printStackTrace();
         }
    }//GEN-LAST:event_jButton2UpdateActionPerformed
     private void Update_Table(){
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        
        try{
            j.con();
            ResultSet rs = j.getdata("SELECT * FROM  exam_timetable");
            
            while (rs.next()) {
            Vector v = new Vector();
            v.add(rs.getString("ExamSubjectID"));
            v.add(rs.getString("Grade"));
             v.add(rs.getString("ExamDay"));
            v.add(rs.getString("Start ExamTime"));
            v.add(rs.getString("End Exam Time"));
            v.add(rs.getString("Venue"));
            dtm.addRow(v);
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
            
        }
        
     }
     
    private void jButton3DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3DeleteActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter subjectId");
        }else{
            try{
                j.con();
                int i = JOptionPane.showConfirmDialog(null,"Are you Sure");
                if(i == 0){
                    j.putdata("DELETE FROM  exam_timetable  WHERE  ExamSubjectID = '"+jTextField1.getText()+ "'");
                    JOptionPane.showMessageDialog(null,"DELETE");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
                e.printStackTrace();
                
            }
            Update_Table();
            clear();
        }
         
         
        
    }//GEN-LAST:event_jButton3DeleteActionPerformed

    private void jButton4SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4SearchActionPerformed
        // TODO add your handling code here
        DefaultTableModel dtm = (DefaultTableModel)  jTable1.getModel();
        dtm.setRowCount(0);
        
        try{
            j.con();
            ResultSet rs = j.getdata("SELECT * FROM  exam_timetable   WHERE  ExamSubjectID ='"+jTextField1.getText()+"'");
            
            while(rs.next()){
                Vector v = new Vector();
            v.add(rs.getString("ExamSubjectID"));
            v.add(rs.getString("Grade"));
            v.add(rs.getString("ExamDay"));
            v.add(rs.getString("Start ExamTime"));
            v.add(rs.getString("End Exam Time"));
            v.add(rs.getString("Venue"));
            dtm.addRow(v);
                
            }
            int i = jTable1.getRowCount();
            if(i == 0){
                JOptionPane.showMessageDialog(null,"No information show");
                jTextField1.setText(null);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Sorry! NO INFORAMTION");
            e.printStackTrace();
        }
       
        
    }//GEN-LAST:event_jButton4SearchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        int selectRowIndex = jTable1.getSelectedRow();
        String subjectId = (String) dtm.getValueAt(selectRowIndex,0);
        
        try{
            j.con();
            ResultSet rs = j.getdata("SELECT * FROM  exam_timetable  WHERE   ExamSubjectID = '"+ subjectId +"'");
            
            while (rs.next()) {
            
            jTextField1.setText(rs.getString("ExamSubjectID"));
            jTextField4.setText(rs.getString("Grade"));
            jDateChooser1.setToolTipText(rs.getString("ExamDay"));
            jTextField3.setText(rs.getString("Start ExamTime"));
            
            jTextField5.setText(rs.getString("End Exam Time"));
            jTextField2.setText(rs.getString("Venue"));
            
           
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1clearActionPerformed
        // TODO add your handling code here:
        
        clear();
    }//GEN-LAST:event_jButton1clearActionPerformed

    private void jButton1printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1printActionPerformed
        try {
            // TODO add your handling code here:
            jTable1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(exam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1printActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1backActionPerformed
        // TODO add your handling code here:
         Main main = new Main();
        main.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_jButton1backActionPerformed
void clear(){
    jTextField1.setText(null);
     jTextField3.setText(null);
     jTextField5.setText(null);
    jDateChooser1.setDate(null);
    jTextField2.setText(null);
     jTextField4.setText(null);
   
   
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Insert;
    private javax.swing.JButton jButton1back;
    private javax.swing.JButton jButton1clear;
    private javax.swing.JButton jButton1print;
    private javax.swing.JButton jButton2Update;
    private javax.swing.JButton jButton3Delete;
    private javax.swing.JButton jButton4Search;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
