/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staffff;

/**
 *
 * @author Ishara Fernando
 */
public class FinanceMain extends javax.swing.JFrame {

    /**
     * Creates new form FinanceMain
     */
    public FinanceMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        maintitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sfsc = new javax.swing.JButton();
        mr = new javax.swing.JButton();
        fdr = new javax.swing.JButton();
        sr = new javax.swing.JButton();
        cblr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(214, 222, 222));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 169, 20), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, -1, -1));

        jPanel2.setBackground(new java.awt.Color(162, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 169, 20), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maintitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        maintitle.setForeground(new java.awt.Color(255, 255, 255));
        maintitle.setText("Finance Management");
        jPanel2.add(maintitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 370, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1810, 90));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Select an Option");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 160, 40));

        sfsc.setBackground(new java.awt.Color(255, 255, 255));
        sfsc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sfsc.setText("Students   Facility & Service Charges");
        sfsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfscActionPerformed(evt);
            }
        });
        jPanel1.add(sfsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 410, 70));

        mr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mr.setText("Maintain Records");
        mr.setMinimumSize(new java.awt.Dimension(359, 31));
        mr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrActionPerformed(evt);
            }
        });
        jPanel1.add(mr, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 410, 70));

        fdr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fdr.setText("Funds & Donations Records");
        fdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdrActionPerformed(evt);
            }
        });
        jPanel1.add(fdr, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 410, 70));

        sr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sr.setText("Salary Records");
        sr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srActionPerformed(evt);
            }
        });
        jPanel1.add(sr, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 560, 410, 70));

        cblr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cblr.setText("Canteen,Bookshop & Library Records");
        cblr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblrActionPerformed(evt);
            }
        });
        jPanel1.add(cblr, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 680, 410, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1810, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrActionPerformed
        MaintainRecords mr1 = new MaintainRecords();
        mr1.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_mrActionPerformed

    private void srActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srActionPerformed
        SalaryRecords sr1 = new SalaryRecords();
        sr1.setVisible(true);
        dispose();
                // TODO add your handling code here:
    }//GEN-LAST:event_srActionPerformed

    private void cblrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblrActionPerformed
        CanteenBookshopAndLibraryRecords   cblr1 = new CanteenBookshopAndLibraryRecords ();
        cblr1.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cblrActionPerformed

    private void sfscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfscActionPerformed
        StudentsFacilityAndServiceCharges sfsc1 = new StudentsFacilityAndServiceCharges();
        sfsc1.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_sfscActionPerformed

    private void fdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdrActionPerformed
        FundsAndDonationRecords fadr1 = new FundsAndDonationRecords();
        fadr1.setVisible(true);
        dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_fdrActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mainhome1 home2 = new mainhome1();
        home2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinanceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinanceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinanceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinanceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinanceMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cblr;
    private javax.swing.JButton fdr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel maintitle;
    private javax.swing.JButton mr;
    private javax.swing.JButton sfsc;
    private javax.swing.JButton sr;
    // End of variables declaration//GEN-END:variables
}
