/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staffff;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ishara Fernando
 */
public class FundsAndDonationRecords extends javax.swing.JFrame {
    
    Connection con = null; 
    PreparedStatement ps = null;
    ResultSet rs = null;


    /**
     * Creates new form FundsAndDonationRecords
     */
    public FundsAndDonationRecords() {
        initComponents();
         con = Database.connect();
         table();
    }
    
     public void table()
    {
        try
        {
            String sql = "SELECT FundsOrDonationID,Type,Date,Charge FROM fundsanddonationrecords ";
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            fadrtable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (Exception e) {}
           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fadrback = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        maintitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fadrtable = new javax.swing.JTable();
        fadrtitle = new javax.swing.JLabel();
        fadrcharge = new javax.swing.JTextField();
        fadrdate = new javax.swing.JTextField();
        fadrtype = new javax.swing.JTextField();
        fadrfodid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fadrsubmit = new javax.swing.JButton();
        fadrupdate = new javax.swing.JButton();
        fadeddelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fadrback.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        fadrback.setText("Back");
        fadrback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fadrbackActionPerformed(evt);
            }
        });
        getContentPane().add(fadrback, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 740, -1, -1));

        jPanel1.setBackground(new java.awt.Color(162, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 169, 20), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maintitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        maintitle.setForeground(new java.awt.Color(255, 255, 255));
        maintitle.setText("Finance Management");
        jPanel1.add(maintitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 400, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1830, 90));

        jPanel2.setBackground(new java.awt.Color(214, 222, 222));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 169, 20), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fadrtable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        fadrtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Type", "Date", "Charge"
            }
        ));
        fadrtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fadrtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(fadrtable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 1010, 380));

        fadrtitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fadrtitle.setText("Funds And Donation Records");
        jPanel2.add(fadrtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 280, 40));

        fadrcharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fadrchargeActionPerformed(evt);
            }
        });
        jPanel2.add(fadrcharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 190, 40));

        fadrdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fadrdateActionPerformed(evt);
            }
        });
        jPanel2.add(fadrdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 190, 40));

        fadrtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fadrtypeActionPerformed(evt);
            }
        });
        jPanel2.add(fadrtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 190, 40));

        fadrfodid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fadrfodidActionPerformed(evt);
            }
        });
        jPanel2.add(fadrfodid, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 190, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Charge :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Date :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Type :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Funds Or Donation ID :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        fadrsubmit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        fadrsubmit.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\Upload.png")); // NOI18N
        fadrsubmit.setText("Submit");
        fadrsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fadrsubmitActionPerformed(evt);
            }
        });
        jPanel2.add(fadrsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, 160, 40));

        fadrupdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        fadrupdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\Save.png")); // NOI18N
        fadrupdate.setText("Update");
        fadrupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fadrupdateActionPerformed(evt);
            }
        });
        jPanel2.add(fadrupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 580, 150, 50));

        fadeddelete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        fadeddelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\cancel.png")); // NOI18N
        fadeddelete.setText("Delete");
        fadeddelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fadeddeleteActionPerformed(evt);
            }
        });
        jPanel2.add(fadeddelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 580, 150, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\a4.png")); // NOI18N
        jButton1.setText("Generate Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 600, 210, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1830, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fadrfodidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fadrfodidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fadrfodidActionPerformed

    private void fadrbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fadrbackActionPerformed
        FinanceMain fm4 = new FinanceMain();
        fm4.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_fadrbackActionPerformed

    private void fadrsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fadrsubmitActionPerformed
       
        String Type = fadrtype.getText();
        String Date = fadrdate.getText();
        String Charge = fadrcharge.getText();
        
         if(Type.isEmpty() || Date .isEmpty() ||   Charge.isEmpty() ){
            JOptionPane.showConfirmDialog(null,"Error!!!");
        }
        else{
            
        int x=JOptionPane.showConfirmDialog(null,"Do you want to add this record");
        if (x==0){
         
         
        try 
        {
            String q ="INSERT INTO `fundsanddonationrecords`(`Type`, `Date`, `Charge`) VALUES ('"+Type+"','" +Date+"','"+Charge+"' )"; 
            ps=con.prepareStatement(q);
            ps.execute();
            table();
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
        }
        }
      }
        
    }//GEN-LAST:event_fadrsubmitActionPerformed

    private void fadrtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fadrtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fadrtypeActionPerformed

    private void fadrtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fadrtableMouseClicked
        // table mouse click
        int r = fadrtable.getSelectedRow();
        String fodid = fadrtable.getValueAt(r, 0).toString();
        String type = fadrtable.getValueAt(r, 1).toString();
        String date = fadrtable.getValueAt(r, 2).toString();
        String charge = fadrtable.getValueAt(r, 3).toString();
        
        fadrfodid.setText(fodid);
        fadrtype.setText(type);
        fadrdate.setText(date);
        fadrcharge.setText(charge);
    }//GEN-LAST:event_fadrtableMouseClicked

    private void fadrupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fadrupdateActionPerformed
          // update
        String fodid = fadrfodid.getText();
        String type = fadrtype.getText();
        String date = fadrdate.getText();
        String charge = fadrcharge.getText();
        
        String q = "UPDATE `fundsanddonationrecords` SET Type ='"+type+"', Date = '"+date+"', Charge = '"+charge+"' where FundsOrDonationID = '"+fodid+"'";
        try{
        ps = con.prepareStatement(q);
        ps.execute();
        table();
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_fadrupdateActionPerformed

    private void fadeddeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fadeddeleteActionPerformed
        // Delete
        String fodid = fadrfodid.getText();
        String q = "DELETE from fundsanddonationrecords where FundsOrDonationID =' "+fodid+"'";
        try{
            ps = con.prepareStatement(q);
            ps.execute();
            table();
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_fadeddeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            fadrtable.print();
        } catch (PrinterException ex) {
            Logger.getLogger(FundsAndDonationRecords.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fadrdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fadrdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fadrdateActionPerformed

    private void fadrchargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fadrchargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fadrchargeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FundsAndDonationRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FundsAndDonationRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FundsAndDonationRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FundsAndDonationRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FundsAndDonationRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fadeddelete;
    private javax.swing.JButton fadrback;
    private javax.swing.JTextField fadrcharge;
    private javax.swing.JTextField fadrdate;
    private javax.swing.JTextField fadrfodid;
    private javax.swing.JButton fadrsubmit;
    private javax.swing.JTable fadrtable;
    private javax.swing.JLabel fadrtitle;
    private javax.swing.JTextField fadrtype;
    private javax.swing.JButton fadrupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maintitle;
    // End of variables declaration//GEN-END:variables
}
