/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staffff;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ishara Fernando
 */
public class MaintainRecords extends javax.swing.JFrame {
    Connection con = null; 
    PreparedStatement ps = null;
    ResultSet rs = null;

    /**
     * Creates new form MaintainRecords
     */
    public MaintainRecords() {
        initComponents();
        con = Database.connect();
        table();
        
    }
    
     public void table()
    {
        try
        {
            String sql = "SELECT MaintainID,MaintainType,Charge FROM maintainrecords ";
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            mrtable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (Exception e) {}
           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        maintitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mrtable = new javax.swing.JTable();
        mrcharge = new javax.swing.JTextField();
        mrmtype = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mrmid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mrTitle = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        mrback = new javax.swing.JButton();
        mrsubmit = new javax.swing.JButton();
        mrupdate = new javax.swing.JButton();
        mrdelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 48, 700, 16));

        jPanel1.setBackground(new java.awt.Color(162, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 169, 20), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maintitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        maintitle.setForeground(new java.awt.Color(255, 255, 255));
        maintitle.setText("Finance Management");
        jPanel1.add(maintitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 380, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1820, 80));

        jPanel2.setBackground(new java.awt.Color(214, 222, 222));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 169, 20), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mrtable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mrtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        mrtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mrtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mrtable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 1150, 330));
        jPanel2.add(mrcharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 190, 40));

        mrmtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrmtypeActionPerformed(evt);
            }
        });
        jPanel2.add(mrmtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 180, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Charge :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Maintain Type :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        mrmid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrmidActionPerformed(evt);
            }
        });
        jPanel2.add(mrmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 180, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Maintain ID :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        mrTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mrTitle.setText("Maintain Records");
        jPanel2.add(mrTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 170, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\a4.png")); // NOI18N
        jButton2.setText("Generate Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 630, 200, 40));

        mrback.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mrback.setText("Back");
        mrback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrbackActionPerformed(evt);
            }
        });
        jPanel2.add(mrback, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 80, 30));

        mrsubmit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mrsubmit.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\Upload.png")); // NOI18N
        mrsubmit.setText("Submit");
        mrsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrsubmitActionPerformed(evt);
            }
        });
        jPanel2.add(mrsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 130, 40));

        mrupdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mrupdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\Save.png")); // NOI18N
        mrupdate.setText("Update");
        mrupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrupdateActionPerformed(evt);
            }
        });
        jPanel2.add(mrupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, 130, 40));

        mrdelete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mrdelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\cancel.png")); // NOI18N
        mrdelete.setText("Delete");
        mrdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrdeleteActionPerformed(evt);
            }
        });
        jPanel2.add(mrdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 550, 130, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1820, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mrmidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrmidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mrmidActionPerformed

    private void mrmtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrmtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mrmtypeActionPerformed

    private void mrbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrbackActionPerformed
        FinanceMain fm3 = new FinanceMain();
        fm3.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_mrbackActionPerformed

    private void mrsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrsubmitActionPerformed
        String MaintainType = mrmtype.getText();
        String Charge = mrcharge.getText();
        
        if(MaintainType.isEmpty() || Charge.isEmpty() ){
            JOptionPane.showConfirmDialog(null,"Error!!!");
        }
        else{
            
        int x=JOptionPane.showConfirmDialog(null,"Do you want to add this record");
        if (x==0){
       
        try 
        {
            String q = "INSERT INTO `maintainrecords`(`MaintainType`, `Charge`) VALUES ('"+MaintainType+"','" +Charge+"')";
            ps=con.prepareStatement(q);
            ps.execute();
            table();
            
        } 
        catch (SQLException e) 
        {
            e.printStackTrace();
        }
        }
        }
    }//GEN-LAST:event_mrsubmitActionPerformed

    private void mrtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mrtableMouseClicked
        // table mouse click
        int r = mrtable.getSelectedRow();
        String mid = mrtable.getValueAt(r, 0).toString();
        String mtype = mrtable.getValueAt(r, 1).toString();
        String charge = mrtable.getValueAt(r, 2).toString();
        
        mrmid.setText(mid);
        mrmtype.setText(mtype);
        mrcharge.setText(charge);
      
        
    }//GEN-LAST:event_mrtableMouseClicked

    private void mrupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrupdateActionPerformed
        // update
        String mid = mrmid.getText();
        String mtype = mrmtype.getText();
        String charge = mrcharge.getText();
        
        
        String q = "UPDATE `maintainrecords` SET MaintainType ='"+mtype+"', Charge = '"+charge+"' where MaintainID = '"+mid+"'";
        try{
        ps = con.prepareStatement(q);
        ps.execute();
        table();
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_mrupdateActionPerformed

    private void mrdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrdeleteActionPerformed
    // Delete
        String mid = mrmid.getText();
        String q = "DELETE from maintainrecords where MaintainID =' "+mid+"'";
        try{
            ps = con.prepareStatement(q);
            ps.execute();
            table();
        }
        catch(Exception e)
        {
            
        }

        
    }//GEN-LAST:event_mrdeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            mrtable.print();
        } catch (PrinterException ex) {
            Logger.getLogger(MaintainRecords.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaintainRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaintainRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaintainRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaintainRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaintainRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel maintitle;
    private javax.swing.JLabel mrTitle;
    private javax.swing.JButton mrback;
    private javax.swing.JTextField mrcharge;
    private javax.swing.JButton mrdelete;
    private javax.swing.JTextField mrmid;
    private javax.swing.JTextField mrmtype;
    private javax.swing.JButton mrsubmit;
    private javax.swing.JTable mrtable;
    private javax.swing.JButton mrupdate;
    // End of variables declaration//GEN-END:variables
}
