/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staffff;


import static com.mysql.cj.MysqlType.SET;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static java.awt.event.PaintEvent.UPDATE;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author DuminduS
 */
public class registerAcademic extends javax.swing.JFrame {

    /**
     * Creates new form registerAcademic
     */
    public registerAcademic() {
        initComponents();
       
    }
    
    
    public void Insert_Update_Delete_Display(){
    
        show_users_in_jtable();
    
    
    }
    //DB j = new DB();
    
     public Connection getConnection() throws SQLException
     {
         Connection con;
         try{
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/s_m_s_01","dumindu","123");
             return con;
         }catch(Exception e){
             e.printStackTrace();
             return null;
         }
     }
     
     public ArrayList<User> getUsersList(){
         
         
         
          ArrayList<User> usersList = new ArrayList<User> ();
         try{
         
         Connection connection = getConnection();
         String query = "SELECT * FROM `staff_register01`";
         Statement st;
         ResultSet rs;
             st = connection.createStatement();
             rs = st.executeQuery(query);
             User user;
             while(rs.next())
             {
                 user = new User(rs.getString("reg_number"),rs.getString("full_name"),rs.getString("gender"),rs.getString("age"),rs.getString("address"),rs.getString("contact_no"),rs.getString("email"),rs.getString("reg_date"));
                 usersList.add(user);
             }
         }catch(Exception e){
             e.printStackTrace();
         }
         
         return usersList;
             
         
     }
             
        //display table in jtable

         public void show_users_in_jtable()
         {
             ArrayList<User> list = getUsersList();
             DefaultTableModel model = (DefaultTableModel)jTable.getModel();
             Object[] row = new Object [8];
             for(int i = 0; i < list.size(); i++)
             {
                 row[0] = list.get(i).getreg_number();
                 row[1] = list.get(i).getfull_name();
                 row[2] = list.get(i).getgender();
                 row[3] = list.get(i).getage();
                 row[4] = list.get(i).getaddress();
                 row[5] = list.get(i).getcontact_no();
                 row[6] = list.get(i).getemail();
                 row[7] = list.get(i).getreg_date();
                 
                 
                 model.addRow(row);
                 
             }
             
         }         
    

         
         //execute the sql query
         
         public void executeSQLQuery(String query , String message) throws SQLException
         {
             Connection con = getConnection();
             Statement st;
             
             try{
                 st = con.createStatement();
                 
                 if((st.executeUpdate(query)) == 1)
                 {
                     
                     //refresh jtable
                     DefaultTableModel model = (DefaultTableModel)jTable.getModel();
                     model.setRowCount(0);
                     show_users_in_jtable();
                     
                     JOptionPane.showMessageDialog(null, "Data"+message+"Successful");
                 }else{
                     JOptionPane.showMessageDialog(null, "Data Not"+message);
                 }    
             }catch(Exception ex){
                 ex.printStackTrace();
             }
         }
         void clear(){
    regnum.setText(null);
    fullname.setText(null);
    gndr.setText(null);
    age01.setText(null);
    address01.setText(null);
    contactno.setText(null);
    email01.setText(null);
    dateChooser1.setText(null);
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        address01 = new javax.swing.JTextField();
        contactno = new javax.swing.JTextField();
        email01 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        regnum = new javax.swing.JTextField();
        gndr = new javax.swing.JTextField();
        age01 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        dateChooser1 = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(160, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 171, 19), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jButton1.setText("ATTENDANCE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 171, 48));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jButton2.setText("LEAVINGS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 171, 49));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jButton4.setText("REGISTER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 171, 50));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 720, -1, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 800));

        jPanel2.setBackground(new java.awt.Color(214, 222, 222));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 169, 20), 4));
        jPanel2.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(162, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 169, 20), 4));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("STAFF MANAGEMENT");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 370, 41));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Full name :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 110, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Gender :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 70, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Age :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 40, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Address : ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Contact No :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Email :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 50, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Register Academic Member");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 260, 30));

        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        jPanel2.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 310, 30));

        address01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address01ActionPerformed(evt);
            }
        });
        jPanel2.add(address01, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 310, 40));

        contactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnoActionPerformed(evt);
            }
        });
        jPanel2.add(contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 190, 30));

        email01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email01ActionPerformed(evt);
            }
        });
        jPanel2.add(email01, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 190, 30));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\images\\Upload.png")); // NOI18N
        jButton8.setText("Submit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 720, 150, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Staff ID");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        regnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnumActionPerformed(evt);
            }
        });
        jPanel2.add(regnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 200, 30));

        gndr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gndrActionPerformed(evt);
            }
        });
        jPanel2.add(gndr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 110, 30));
        jPanel2.add(age01, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 110, 30));

        jTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STAFF ID", "FULL NAME", "GENDER", "AGE", "ADDRESS", "CONTACT NO", "EMAIL", "Reg Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 1000, 450));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\images\\Save.png")); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 720, 150, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\images\\cancel.png")); // NOI18N
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 720, 170, 40));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\images\\a4.png")); // NOI18N
        jButton9.setText("Generate report");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 700, 180, 50));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\images\\View.png")); // NOI18N
        jButton10.setText("Search");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\images\\a1.png")); // NOI18N
        jButton7.setText("Register Non Academic member");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 100, 500, 50));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 710, 80, 20));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton11.setText("Clear");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 720, 110, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Reg Date :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 80, 30));
        jPanel2.add(dateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 640, 180, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1610, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        attendance satten = new attendance();
        satten.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        leavings sLeave = new leavings();
        sLeave.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        mainhome1 home11 = new mainhome1();
        home11.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        registerNonAc sNonreg = new registerNonAc();
        sNonreg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void address01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address01ActionPerformed

    private void contactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnoActionPerformed

    private void email01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email01ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //INSERT
        String reg_number = regnum.getText();
        String full_name =  fullname.getText();
        String gender = gndr.getText();
        String age = age01.getText();
        String address = address01.getText();
        String contact_no = contactno.getText();
        String email = email01.getText();
        String regDate = dateChooser1.getText();
        //Date date = new Date();
        //SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
        //day = sdf.format(date);
        //||day.isEmpty()
        //'"+Date01.getDate()+"'
        //,Reg_date
        
        if(reg_number.isEmpty() || regnum.getText().trim().length() != 4 || full_name.isEmpty() || gender.isEmpty() || age.isEmpty() || address.isEmpty() || contact_no.isEmpty() || email.isEmpty() || regDate.isEmpty() ){
            JOptionPane.showMessageDialog(null,"Error!!");
        }
        else{
            
        int x=JOptionPane.showConfirmDialog(null,"Do you want to add this record");
        if (x==0){
        
        String query = "INSERT INTO staff_register01(reg_number,full_name,gender,age,address,contact_no,email,reg_date) Values('"+regnum.getText()+"','"+fullname.getText()+"','"+gndr.getText()+"','"+age01.getText()+"','"+address01.getText()+"','"+contactno.getText()+"','"+email01.getText()+"','"+dateChooser1.getText()+"');";
        
        try {
            executeSQLQuery(query,"Inserted");
            
        } catch (SQLException ex) {
            Logger.getLogger(registerAcademic.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex.getMessage());
            
           
        }
        
        } 
    }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void regnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnumActionPerformed

    private void gndrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gndrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gndrActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
       //display selected row in form
       
       int i = jTable.getSelectedRow();
       TableModel model = jTable.getModel();
       regnum.setText(model.getValueAt(i,0).toString());
       fullname.setText(model.getValueAt(i,1).toString());
       gndr.setText(model.getValueAt(i,2).toString());
       age01.setText(model.getValueAt(i,3).toString());
       address01.setText(model.getValueAt(i,4).toString());
       contactno.setText(model.getValueAt(i,5).toString());
       email01.setText(model.getValueAt(i,6).toString());
       dateChooser1.setText(model.getValueAt(i,7).toString());
       
    }//GEN-LAST:event_jTableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //UPDATE
        
        String reg_number = regnum.getText();
        String full_name =  fullname.getText();
        String gender = gndr.getText();
        String age = age01.getText();
        String address = address01.getText();
        String contact_no = contactno.getText();
        String email = email01.getText();
        String regDate = dateChooser1.getText();
        
        
        if(reg_number.isEmpty() || full_name.isEmpty() || gender.isEmpty() || age.isEmpty() || address.isEmpty() || contact_no.isEmpty() || email.isEmpty() || regDate.isEmpty() ){
            JOptionPane.showMessageDialog(null,"Error!!");
        }
        else{
            
        int x=JOptionPane.showConfirmDialog(null,"Do you want to update..?");
        if (x==0){
        
        
        String query = "UPDATE staff_register01 SET full_name='"+fullname.getText()+"',gender='"+gndr.getText()+"',age='"+age01.getText()+"',address='"+address01.getText()+"',contact_no='"+contactno.getText()+"',email='"+email01.getText()+"',reg_date='"+dateChooser1.getText()+"'where reg_number='"+regnum.getText()+"';";
        try {
            executeSQLQuery(query,"Updated");
        } catch (SQLException ex) {
            Logger.getLogger(registerAcademic.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed
        
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //DELETE
        
        String query = "DELETE FROM staff_register01 WHERE reg_number = '"+regnum.getText()+"'";
        try {
            executeSQLQuery(query,"Deleted");
            
        } catch (SQLException ex) {
            Logger.getLogger(registerAcademic.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Insert_Update_Delete_Display();
    }//GEN-LAST:event_formWindowOpened

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            // TODO add your handling code here:
            jTable.print();
        } catch (PrinterException ex) {
            Logger.getLogger(registerAcademic.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         Connection connection;
        try {
            connection = DBclass.getConnection();
       
        
           PreparedStatement pre1;
     
            pre1 = connection.prepareStatement("select *  from staff_register01 where reg_number= ?   ");
            pre1.setString(1 , regnum.getText() );
            ResultSet rs = pre1.executeQuery();
            String regnum ="" ;
            String fullname ="" ;
            String gndr ="" ;
            String age01 ="" ;
            String address01 ="" ;
            String contactno ="" ;
            String email01 ="" ;
            String dateChooser1 ="" ;
           
         
            while(rs.next())
            {
                regnum = rs.getString(1);
                fullname = rs.getString(2);
                gndr  = rs.getString(3);
                age01 = rs.getString(4);
                 address01 = rs.getString(5);
                  contactno = rs.getString(6);
                   email01 = rs.getString(7);
                   dateChooser1 = rs.getString(8);
              
            
            
            this.regnum.setText(regnum);
            this.fullname.setText(fullname);
           this.gndr.setText(gndr);
            this.age01.setText(age01);
            this.address01.setText(address01);
            this.contactno.setText(contactno);
            this.email01.setText(email01);
            this.dateChooser1.setText(dateChooser1);
           
            }
    }   catch (Exception ex) {
            System.out.println(ex);
        }
                                            

        
                                
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerAcademic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address01;
    private javax.swing.JTextField age01;
    private javax.swing.JTextField contactno;
    private datechooser.beans.DateChooserCombo dateChooser1;
    private javax.swing.JTextField email01;
    private javax.swing.JTextField fullname;
    private javax.swing.JTextField gndr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField regnum;
    // End of variables declaration//GEN-END:variables
}
