/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package staffff;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author DuminduS
 */
public class registerNonAc extends javax.swing.JFrame {

    /** Creates new form registerNonAc */
    public registerNonAc() {
        initComponents();
    }
    
     public void Insert_Update_Delete_Display(){
    
        show_users_in_jtable();
    
    
    }
    
     public Connection getConnection() throws SQLException
     {
         Connection con;
         try{
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/s_m_s_01","dumindu","123");
             return con;
         }catch(Exception e){
             e.printStackTrace();
             return null;
         }
     }
     
     public ArrayList<User02> getUsersList(){
         
         
         
          ArrayList<User02> usersList02 = new ArrayList<User02> ();
         try{
         
         Connection connection = getConnection();
         String query = "SELECT * FROM `staff_register02";
         Statement st;
         ResultSet rs;
             st = connection.createStatement();
             rs = st.executeQuery(query);
             User02 user02;
             while(rs.next())
             {
                 user02 = new User02(rs.getString("reg_num"),rs.getString("f_name"),rs.getString("genderr"),rs.getString("agee"),rs.getString("addresss"),rs.getString("contct_no"),rs.getString("mail"),rs.getString("reg_date01"));
                 usersList02.add(user02);
             }
         }catch(Exception e){
             e.printStackTrace();
         }
         
         return usersList02;
             
         
     }
             
        //display table in jtable

         public void show_users_in_jtable()
         {
             ArrayList<User02> list = getUsersList();
             DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
             Object[] row = new Object [8];
             for(int i = 0; i < list.size(); i++)
             {
                 row[0] = list.get(i).getreg_number02();
                 row[1] = list.get(i).getfull_name02();
                 row[2] = list.get(i).getgender02();
                 row[3] = list.get(i).getage02();
                 row[4] = list.get(i).getaddress02();
                 row[5] = list.get(i).getcontact_no02();
                 row[6] = list.get(i).getemail02();
                 row[7] = list.get(i).getreg_date01();
                 
                 model.addRow(row);
                 
             }
             
         }         
    

         
         //execute the sql query
         
         public void executeSQLQuery(String query , String message) throws SQLException
         {
             Connection con = getConnection();
             Statement st;
             
             try{
                 st = con.createStatement();
                 if((st.executeUpdate(query)) == 1)
                 {
                     
                     //refresh jtable
                     DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
                     model.setRowCount(0);
                     show_users_in_jtable();
                     
                     JOptionPane.showMessageDialog(null, "Data"+message+"Successful");
                 }else{
                     JOptionPane.showMessageDialog(null, "Data Not"+message);
                 }    
             }catch(Exception ex){
                 ex.printStackTrace();
             }
         }
         
         void clear(){
    regnum1.setText(null);
    fullname1.setText(null);
    gndr1.setText(null);
    age011.setText(null);
    address011.setText(null);
    contactno1.setText(null);
    email011.setText(null);
    dateChooser2.setText(null);
         }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fullname1 = new javax.swing.JTextField();
        address011 = new javax.swing.JTextField();
        contactno1 = new javax.swing.JTextField();
        email011 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        regnum1 = new javax.swing.JTextField();
        gndr1 = new javax.swing.JTextField();
        age011 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        dateChooser2 = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(160, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 169, 20), 4));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jButton1.setText("ATTENDANCE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 171, 48));

        jButton2.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jButton2.setText("LEAVINGS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 171, 49));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jButton4.setText("REGISTER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 171, 50));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, -1, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 800));

        jPanel2.setBackground(new java.awt.Color(215, 221, 221));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 169, 20), 4));
        jPanel2.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(160, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 169, 20), 4));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("STAFF MANAGEMENT");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 370, 41));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Full name :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 110, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Gender :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 70, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Age :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 40, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Address : ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Contact No :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Email :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 50, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Register Non Academic Member");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 320, 30));

        fullname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullname1ActionPerformed(evt);
            }
        });
        jPanel2.add(fullname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 320, 30));

        address011.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address011ActionPerformed(evt);
            }
        });
        jPanel2.add(address011, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 200, 60));

        contactno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactno1ActionPerformed(evt);
            }
        });
        jPanel2.add(contactno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 140, -1));

        email011.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email011ActionPerformed(evt);
            }
        });
        jPanel2.add(email011, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 240, 30));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\images\\Upload.png")); // NOI18N
        jButton8.setText("Submit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 700, 160, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Registration Num :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        regnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnum1ActionPerformed(evt);
            }
        });
        jPanel2.add(regnum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 190, 30));

        gndr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gndr1ActionPerformed(evt);
            }
        });
        jPanel2.add(gndr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 110, -1));
        jPanel2.add(age011, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 100, 30));

        jTable2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STAFF ID", "FULL NAME", "GENDER", "AGE", "ADDRESS", "CONTACT NO", "EMAIL", "Reg Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 1060, 480));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\images\\Save.png")); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 700, 170, 40));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\images\\cancel.png")); // NOI18N
        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 700, 180, 40));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\images\\a4.png")); // NOI18N
        jButton9.setText("Generate report");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 700, 180, 50));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\images\\View.png")); // NOI18N
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton10.setText("Clear");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 700, 100, 30));
        jPanel2.add(dateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, 230, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Reg Date :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1620, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        attendance satten = new attendance();
        satten.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        leavings sLeave = new leavings();
        sLeave.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        registerAcademic sAccademic = new registerAcademic();
        sAccademic.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         mainhome1 home11 = new mainhome1();
        home11.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void fullname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullname1ActionPerformed

    private void address011ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address011ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address011ActionPerformed

    private void contactno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactno1ActionPerformed

    private void email011ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email011ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email011ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

         //INSERT
        
        String reg_number1 = regnum1.getText();
       
        String full_name1 =  fullname1.getText();
        String gender1 = gndr1.getText();
        String age1 = age011.getText();
        String address1 = address011.getText();
        String contact_no1 = contactno1.getText();
        String email1 = email011.getText();
        String reg_date01 = dateChooser2.getText();
        
        if(reg_number1.isEmpty() || regnum1.getText().trim().length() != 4 || full_name1.isEmpty() || gender1.isEmpty() || age1.isEmpty() || address1.isEmpty() || contact_no1.isEmpty() || email1.isEmpty() ||reg_date01.isEmpty() ){
            JOptionPane.showMessageDialog(null,"Error");
        }
        else{
            
        int x=JOptionPane.showConfirmDialog(null,"Do you want to add this record");
        if (x==0){
        
        String query = "INSERT INTO staff_register02(reg_num,f_name,genderr,agee,addresss,contct_no,mail,reg_date01) Values('"+regnum1.getText()+"','"+fullname1.getText()+"','"+gndr1.getText()+"','"+age011.getText()+"','"+address011.getText()+"','"+contactno1.getText()+"','"+email011.getText()+"','"+dateChooser2.getText()+"');"; 
        try {
            executeSQLQuery(query,"Inserted");
        } catch (SQLException ex) {
            Logger.getLogger(registerAcademic.class.getName()).log(Level.SEVERE, null, ex);
        }
        } 
    }
         
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void regnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnum1ActionPerformed

    private void gndr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gndr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gndr1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        //display selected row in form
       
       int i = jTable2.getSelectedRow();
       TableModel model = jTable2.getModel();
       regnum1.setText(model.getValueAt(i,0).toString());
       fullname1.setText(model.getValueAt(i,1).toString());
       gndr1.setText(model.getValueAt(i,2).toString());
       age011.setText(model.getValueAt(i,3).toString());
       address011.setText(model.getValueAt(i,4).toString());
       contactno1.setText(model.getValueAt(i,5).toString());
       email011.setText(model.getValueAt(i,6).toString());
       dateChooser2.setText(model.getValueAt(i,7).toString());
       
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         //UPDATE
         
        String reg_number1 = regnum1.getText();
       
        String full_name1 =  fullname1.getText();
        String gender1 = gndr1.getText();
        String age1 = age011.getText();
        String address1 = address011.getText();
        String contact_no1 = contactno1.getText();
        String email1 = email011.getText();
        String reg_date01 = dateChooser2.getText();
        
        if(reg_number1.isEmpty() || full_name1.isEmpty() || gender1.isEmpty() || age1.isEmpty() || address1.isEmpty() || contact_no1.isEmpty() || email1.isEmpty() ||reg_date01.isEmpty() ){
            JOptionPane.showMessageDialog(null,"Error");
        }
        else{
            
        int x=JOptionPane.showConfirmDialog(null,"Do you want to update..?");
        if (x==0){
         
         
        String query = "UPDATE staff_register02 SET f_name='"+fullname1.getText()+"',genderr='"+gndr1.getText()+"',agee='"+age011.getText()+"',addresss='"+address011.getText()+"',contct_no='"+contactno1.getText()+"',mail='"+email011.getText()+"',reg_date01='"+dateChooser2.getText()+"'where reg_num='"+regnum1.getText()+"';";
        try {
            executeSQLQuery(query,"Updated");
        } catch (SQLException ex) {
            Logger.getLogger(registerNonAc.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //DELETE
        
        String query = "DELETE FROM `staff_register02` WHERE reg_num = '"+regnum1.getText()+"'";
        try {
            executeSQLQuery(query,"Deleted");
        } catch (SQLException ex) {
            Logger.getLogger(registerAcademic.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Insert_Update_Delete_Display();
    }//GEN-LAST:event_formWindowOpened

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            // TODO add your handling code here:
            jTable2.print();
        } catch (PrinterException ex) {
            Logger.getLogger(registerNonAc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       
        Connection connection;
        try {
            connection = DBclass.getConnection();
       
        
           PreparedStatement pre1;
     
            pre1 = connection.prepareStatement("select *  from staff_register02 where reg_num= ?   ");
            pre1.setString(1 , regnum1.getText() );
            ResultSet rs = pre1.executeQuery();
            String regnum1 ="" ;
            String fullname1 ="" ;
            String gndr1 ="" ;
            String age011 ="" ;
            String address011 ="" ;
            String contactno1 ="" ;
            String email011 ="" ;
            String dateChooser2 ="" ;
           
         
            while(rs.next())
            {
                regnum1 = rs.getString(1);
                fullname1 = rs.getString(2);
                gndr1  = rs.getString(3);
                age011 = rs.getString(4);
                 address011 = rs.getString(5);
                  contactno1 = rs.getString(6);
                   email011 = rs.getString(7);
                   dateChooser2 = rs.getString(8);
              
            
            
            this.regnum1.setText(regnum1);
            this.fullname1.setText(fullname1);
           this.gndr1.setText(gndr1);
            this.age011.setText(age011);
            this.address011.setText(address011);
            this.contactno1.setText(contactno1);
            this.email011.setText(email011);
            this.dateChooser2.setText(dateChooser2);
           
            }
    }   catch (Exception ex) {
            System.out.println(ex);
        }
                                            
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerNonAc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerNonAc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerNonAc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerNonAc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerNonAc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address011;
    private javax.swing.JTextField age011;
    private javax.swing.JTextField contactno1;
    private datechooser.beans.DateChooserCombo dateChooser2;
    private javax.swing.JTextField email011;
    private javax.swing.JTextField fullname1;
    private javax.swing.JTextField gndr1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField regnum1;
    // End of variables declaration//GEN-END:variables

}
