/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staffff;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Ishara Fernando
 */
public class StudentsFacilityAndServiceCharges extends javax.swing.JFrame {

    Connection con = null; 
    PreparedStatement ps = null;
    ResultSet rs = null;
    /**
     * Creates new form StudentsFacilityAndServiceCharges
     */
    public StudentsFacilityAndServiceCharges() {
        initComponents();
        con = Database.connect();
        table();
    }
    
    public void table()
    {
        try
        {
            String sql = "SELECT InvoiceID,StudentID,Year,Cost FROM students ";
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            sfasctable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (Exception e) {}
           
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sfascinid = new javax.swing.JTextField();
        sfascsid = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        maintitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        sfasccost = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sfascyear = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sfascsearch = new javax.swing.JButton();
        sfascs = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sfscTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sfasctable = new javax.swing.JTable();
        sfascsubmit = new javax.swing.JButton();
        sfascback = new javax.swing.JButton();
        sfascupdate = new javax.swing.JButton();
        sfascdelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(sfascinid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 200, 30));
        getContentPane().add(sfascsid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 200, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, 700, 16));

        jPanel1.setBackground(new java.awt.Color(162, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 169, 20), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maintitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        maintitle.setForeground(new java.awt.Color(255, 255, 255));
        maintitle.setText("Finance Management");
        jPanel1.add(maintitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 360, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1820, 80));

        jPanel2.setBackground(new java.awt.Color(214, 222, 222));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 169, 20), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(sfasccost, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 200, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cost :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, -1));

        sfascyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfascyearActionPerformed(evt);
            }
        });
        jPanel2.add(sfascyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 140, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Year :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Student ID :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Invoice ID  :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        sfascsearch.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sfascsearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\View.png")); // NOI18N
        sfascsearch.setText("Search");
        sfascsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfascsearchActionPerformed(evt);
            }
        });
        jPanel2.add(sfascsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 140, 40));
        jPanel2.add(sfascs, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 180, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Student ID");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        sfscTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sfscTitle.setText("Students Facility And Service Charges");
        jPanel2.add(sfscTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 390, 47));

        sfasctable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sfasctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sfasctable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sfasctableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sfasctable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 1050, 370));

        sfascsubmit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sfascsubmit.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\Upload.png")); // NOI18N
        sfascsubmit.setText("Submit");
        sfascsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfascsubmitActionPerformed(evt);
            }
        });
        jPanel2.add(sfascsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 590, 140, 40));

        sfascback.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sfascback.setText("Back");
        sfascback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfascbackActionPerformed(evt);
            }
        });
        jPanel2.add(sfascback, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, 80, 30));

        sfascupdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sfascupdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\Save.png")); // NOI18N
        sfascupdate.setText("Update");
        sfascupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfascupdateActionPerformed(evt);
            }
        });
        jPanel2.add(sfascupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 590, 130, 40));

        sfascdelete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sfascdelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\cancel.png")); // NOI18N
        sfascdelete.setText("Delete");
        sfascdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfascdeleteActionPerformed(evt);
            }
        });
        jPanel2.add(sfascdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 590, 140, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DuminduS\\Desktop\\New folder\\New folder\\a4.png")); // NOI18N
        jButton1.setText("Generate Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 640, 170, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1820, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sfascyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfascyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sfascyearActionPerformed

    private void sfascbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfascbackActionPerformed
        FinanceMain fm2 = new FinanceMain();
        fm2.setVisible(true);
        dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_sfascbackActionPerformed

    private void sfascsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfascsubmitActionPerformed
    
         String studentID = sfascsid.getText();
         String date = sfascyear.getText();
         String cost = sfasccost.getText();
         
       
          if(studentID.isEmpty() ||sfascsid.getText().trim().length() != 4 ||date.isEmpty() ||  cost.isEmpty() ){
            JOptionPane.showConfirmDialog(null,"Error!!!");
        }
        else{
            
        int x=JOptionPane.showConfirmDialog(null,"Do you want to add this record");
        if (x==0){
         
         
        try 
        { 
            String q = "INSERT INTO `students`(StudentID,Year,Cost) VALUES ('"+studentID+"','"+date+"','"+cost+"')";
            ps=con.prepareStatement(q);
            ps.execute();
            table();
        } 
        catch (Exception ex) 
        {
            ex.printStackTrace();
        }
        }
          }
    }//GEN-LAST:event_sfascsubmitActionPerformed

    private void sfasctableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sfasctableMouseClicked
        // table mouse click
        int r = sfasctable.getSelectedRow();
        String inid = sfasctable.getValueAt(r, 0).toString();
        String sid = sfasctable.getValueAt(r, 1).toString();
        String year = sfasctable.getValueAt(r, 2).toString();
        String cost = sfasctable.getValueAt(r, 3).toString();
        
        sfascinid.setText(inid);
        sfascsid.setText(sid);
        sfascyear.setText(year);
        sfasccost.setText(cost);
        
       
       
       
        
        
         
    }//GEN-LAST:event_sfasctableMouseClicked

    private void sfascupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfascupdateActionPerformed
        //update
        String inid = sfascinid.getText();
        String sid = sfascsid.getText();
        String year =sfascyear.getText();
        String cost = sfasccost.getText();
        
        String q = "UPDATE `students` SET StudentID ='"+sid+"', Year = '"+year+"', Cost = '"+cost+"' where InvoiceID = '"+inid+"'";
        try{
        ps = con.prepareStatement(q);
        ps.execute();
        table();
        }
        catch(Exception e){
            
        }
        
        
        
    }//GEN-LAST:event_sfascupdateActionPerformed

    private void sfascdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfascdeleteActionPerformed
        // Delete
        String inid = sfascinid.getText();
        String q = "DELETE from students where InvoiceID =' "+inid+"'";
        try{
            ps = con.prepareStatement(q);
            ps.execute();
            table();
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_sfascdeleteActionPerformed

    private void sfascsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfascsearchActionPerformed
        // search
        String sname = sfascs.getText();
        String q = "SELECT InvoiceID,StudentID,Year,Cost from students where StudentID LIKE '%" +sname+ "%'";  
        
        try{
            ps = con.prepareStatement(q);
            rs = ps.executeQuery();
           sfasctable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_sfascsearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            sfasctable.print();
        } catch (PrinterException ex) {
            Logger.getLogger(StudentsFacilityAndServiceCharges.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsFacilityAndServiceCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsFacilityAndServiceCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsFacilityAndServiceCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsFacilityAndServiceCharges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentsFacilityAndServiceCharges().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel maintitle;
    private javax.swing.JButton sfascback;
    private javax.swing.JTextField sfasccost;
    private javax.swing.JButton sfascdelete;
    private javax.swing.JTextField sfascinid;
    private javax.swing.JTextField sfascs;
    private javax.swing.JButton sfascsearch;
    private javax.swing.JTextField sfascsid;
    private javax.swing.JButton sfascsubmit;
    private javax.swing.JTable sfasctable;
    private javax.swing.JButton sfascupdate;
    private javax.swing.JTextField sfascyear;
    private javax.swing.JLabel sfscTitle;
    // End of variables declaration//GEN-END:variables
}
